spring:
  profiles:
    active: dev
  datasource:
    url: ${DB_URL}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    hikari:
      maximum-pool-size: 5
      connection-timeout: 60000
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  application:
    name: deneasybot
  mail:
    host: sandbox.smtp.mailtrap.io
    port: 2525
    username: ${MAILTRAP_USER}
    password: ${MAILTRAP_PASS}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

jwt:
  secret: ${JWT_SECRET}

omie:
  api:
   users:
     url: https://app.omie.com.br/api/v1/crm/usuarios/
   companies:
     url: https://app.omie.com.br/api/v1/geral/empresas/
   movements:
     url: https://app.omie.com.br/api/v1/financas/mf/
   categories:
     url: https://app.omie.com.br/api/v1/geral/categorias/

whatsapp:
  verify-token: ${WHATSAPP_VERIFY_TOKEN}
  api:
    url: ${WHATSAPP_API_URL}
    token: ${WHATSAPP_API_TOKEN}