spring:
  profiles:
    active: prod
  datasource:
    url: ${DB_URL}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    hikari:
      maximum-pool-size: 5
      connection-timeout: 60000
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  application:
    name: deneasybot
  mail:
    host: sandbox.smtp.mailtrap.io
    port: 2525
    username: ${MAILTRAP_USER}
    password: ${MAILTRAP_PASS}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

jwt:
  secret: ${JWT_SECRET}

deneasy:
  encryption:
    secret-key: ${DENEASY_ENCRYPTION_SECRET}
    salt: ${DENEASY_ENCRYPTION_SALT}
  security:
    cookie-secure: false

omie:
  api:
   users:
     url: https://app.omie.com.br/api/v1/crm/usuarios/
   companies:
     url: https://app.omie.com.br/api/v1/geral/empresas/
   movements:
     url: https://app.omie.com.br/api/v1/financas/mf/
   categories:
     url: https://app.omie.com.br/api/v1/geral/categorias/
   summary:
     url: https://app.omie.com.br/api/v1/financas/resumo/

whatsapp:
  verify-token: ${WHATSAPP_VERIFY_TOKEN}
  app-secret: ${WHATSAPP_APP_SECRET}
  api:
    url: ${WHATSAPP_API_URL}
    token: ${WHATSAPP_API_TOKEN}

management:
  endpoints:
    web:
      exposure:
        include: "health"
  endpoint:
    health:
      show-details: "never"

resilience4j:
  ratelimiter:
    instances:
      omieApi:
        limitForPeriod: 4
        limitRefreshPeriod: 1s
        timeoutDuration: 5s
  bulkhead:
    instances:
      omieApi:
        maxConcurrentCalls: 4
        maxWaitDuration: 10s
  retry:
    instances:
      omieApi:
        maxAttempts: 3
        waitDuration: 500ms